<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FEQ3OA0" failures="1" tests="2" name="runner.RunTest" time="38.215" errors="0" timestamp="2022-12-17T12:52:29 IST" skipped="0">
  <testcase classname="runner.RunTest" name="runScenario" time="24.584">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at pages.LegalEntitiesPage.verifyEditSaved(LegalEntitiesPage.java:109)
at steps.EditLegalEntity.verify_edit_is_saved(EditLegalEntity.java:83)
at âœ½.Verify Edit is saved(file:///C:/Users/Karthik/Eclipse%20Workspace/Selenium-AutomationBootCamp/SalesforceCucumber/src/main/java/features/EditLegalEntity.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.RunTest" name="runScenario" time="13.631"/>
  <system-out/>
</testsuite> <!-- runner.RunTest -->
